print('hello world!')
print("hej!")
imie = input("Jak masz na imie?\n")
print("Cześć", imie + ", miło cię poznać :)")
print("Ile masz lat?")
wiek = input()
print("Z jakiego peronu dostaniesz się do Hogwartu?")
peron = input()
print("W wieku", wiek, "chyba nie ma już sensu jechać na peron", peron)
input()

print("hej! Jak masz na imię?")
imie = input()
print(imie, "pomogę Ci obliczyć współczynnik BMI")
print("po pierwsze powiedz mi ile ważysz?")
waga = float(input())
print("ok, potrzebny będzie również Twój wzrost podany w metrach")
wzrost = float(input())
print("Świetnie!")
BMI = waga / (wzrost ** 2)
print("Zatem, Twoje bmi wynosi:", BMI)
input()

szer = 42
print("-" * szer)
print("|  Czas  |     Zawodnik     |    Data    |")
print("*" * szer)
print("| %6.3f | %16s | %10s |" % (9.58, "Usain Bolt", "16.08.2009"))
print("| %6.3f | %16s | %10s |" % (9.69, "Tyson Gay", "20.09.2009"))
print("| %6.3f | %16s | %10s |" % (9.69, "Yohan Blake", "23.09.2012"))
print("| %6.3f | %16s | %10s |" % (9.74, "Asafa Powell", "2.09.2008"))
print("-" * szer)
